name: CI

on:
  push:
    branches: [main]
  # pull_request:
    # branches: [main]

  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Install node.js
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.2
        with:
          # Version Spec of the version to use. Examples: 12.x, 10.15.1, >=10.15.0.
          node-version: 16.15.1
          
      # Install mocha for tests
      - name: Installation of Mocha for tests
        run: |
          cd src;
          npm install -g mocha;
          npm install

      - name: Test execution
        run: mocha src/test/convert.js
        
      # - name: Ru a one-line script
        # run: echo Hello, world!

      # - name: Run a multi-line script
        # run: |
          # echo add another actions to build,
          # echo test, and deploy your project.

      - name: Docker Login
        uses: docker/login-action@v3.1.0
        with:
          # Username used to log against the Docker registry
          username: ${{secrets.DOCKERHUB_USERNAME}}
          # Password or personal access token used to log against the Docker registry
          password: ${{secrets.DOCKERHUB_PASSWORD}}
          
      # Build docker image
      - name: Build and push Docker images
        uses: docker/build-push-action@v5.3.0
        with:
          context: ./src
          # Path to the Dockerfile
          file: ./src/Dockefile
          push: true
          tags: |
            danilomarques/aula-github-action-conv-temp:v1
            danilomarqeus/aula-github-action-conv-temp:latest
                
