name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Ru a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo add another actions to build,
          echo test, and deploy your project.
