name: CI

on:
  push:
    branches: [main]
  # pull_request:
    # branches: [main]

  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.2
        with:
          # Version Spec of the version to use. Examples: 12.x, 10.15.1, >=10.15.0.
          node-version: 16.15.1

      - name: Installation of Mocha for tests
        run: |
          cd src;
          npm install -g mocha;
          npm install
          
      # - name: Ru a one-line script
        # run: echo Hello, world!

      # - name: Run a multi-line script
        # run: |
          # echo add another actions to build,
          # echo test, and deploy your project.
